# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    tty: true
    volumes: 
      - .:/opt/app
      - /opt/app/node_modules
    depends_on: 
      - pgadmin4
      - db
    environment: 
      - HOST_DB=db
    command: npm run start:dev

  db:
    image: postgres
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./DB/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ExampleDB

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    depends_on: 
      - db
    environment: 
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: example

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
